### ISSUE TITLE
Add Google Fit support

### ISSUE THREAD

**Issue by dgomes** [dgomes/openvidonn#1]
Add Google Fit support

**Comment by ghost** [comment]
@dgomes Any progress with this? :D

**Comment by dgomes** [comment]
Hi sorry, but I bought an Android Wear watch and completely dropped the vidonn bracelet :(

**Comment by hipio** [comment]
@dgomes To bad. Would have loved this for the X6 and I can't seem to get the project itself working on Android Studio.
