### ISSUE TITLE
Skin temperature sensor?

### ISSUE THREAD

**Issue by robinvanemden** [dgomes/openvidonn#3]
Hi Diogo, thank you for OpenVidonn! OpenVidonn is much better than the official Vidonn app - and open to boot. One question: I wondered if you've found any temperature sensor support in the BLE profile of the X5? I read somewhere that the X5 might support skin temperature measurement - probably a misprint - still, it would be great if it would support even rudimentary skin temperature measurements.

**Comment by dgomes** [comment]
Browsing the Device Bluetooth profile, can't find anything.

so sorry

**Comment by robinvanemden** [comment]
Figures - thank you for browsing the Bluetooth profile though!
